import {
  bigint,
  boolean,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  uniqueIndex,
} from "drizzle-orm/pg-core";

const auditColumns = () => ({
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  recordJson: jsonb("record_json").notNull(),
});

/** Indexed projection of each authoritative Claim object. */
export const claims = pgTable("claims", {
  claimId: text("claim_id").primaryKey(),
  network: text("network").notNull(),
  packageId: text("package_id").notNull(),
  registryObjectId: text("registry_object_id").notNull(),
  objectVersion: text("object_version"),
  objectDigest: text("object_digest"),
  transactionDigest: text("transaction_digest"),
  checkpoint: bigint("checkpoint", { mode: "number" }),
  packageVersion: integer("package_version").notNull().default(1),
  coinType: text("coin_type").notNull(),
  mode: integer("mode").notNull(),
  state: integer("state").notNull(),
  creator: text("creator"),
  statement: text("statement").notNull(),
  resolutionCriteria: text("resolution_criteria").notNull(),
  deadlines: jsonb("deadlines").notNull(),
  committeeBudget: text("committee_budget").notNull(),
  evidenceBudget: text("evidence_budget").notNull(),
  submittedText: text("submitted_text"),
  submittedUrls: jsonb("submitted_urls").notNull(),
  statementBlobId: text("statement_blob_id"),
  criteriaBlobId: text("criteria_blob_id"),
  evidencePolicyId: text("evidence_policy_id").notNull(),
  proposedOutcome: integer("proposed_outcome"),
  committeeId: text("committee_id"),
  certificateId: text("certificate_id"),
  result: text("result"),
  truthScoreBps: integer("truth_score_bps"),
  ...auditColumns(),
});

export const committees = pgTable("committees", {
  committeeId: text("committee_id").primaryKey(),
  claimId: text("claim_id").notNull(),
  phase: integer("phase").notNull(),
  roundTallyId: text("round_tally_id").notNull(),
  agentProfileIds: jsonb("agent_profile_ids").notNull(),
  jurySeatIds: jsonb("jury_seat_ids").notNull(),
  reserveAgentProfileIds: jsonb("reserve_agent_profile_ids").notNull(),
  randomnessTransactionDigest: text("randomness_transaction_digest"),
  locked: boolean("locked").notNull().default(false),
  ...auditColumns(),
});

export const jurySeats = pgTable("jury_seats", {
  jurySeatId: text("jury_seat_id").primaryKey(),
  claimId: text("claim_id").notNull(),
  committeeId: text("committee_id").notNull(),
  agentProfileId: text("agent_profile_id").notNull(),
  agentOwner: text("agent_owner").notNull(),
  agentCapId: text("agent_cap_id"),
  phase: integer("phase").notNull(),
  status: text("status").notNull(),
  evidenceRoot: text("evidence_root"),
  commitment: text("commitment"),
  runHash: text("run_hash"),
  ...auditColumns(),
});

export const roundTallies = pgTable("round_tallies", {
  roundTallyId: text("round_tally_id").primaryKey(),
  claimId: text("claim_id").notNull(),
  committeeId: text("committee_id").notNull(),
  phase: integer("phase").notNull(),
  expectedJurySeatIds: jsonb("expected_jury_seat_ids").notNull(),
  revealedJurySeatIds: jsonb("revealed_jury_seat_ids").notNull(),
  revealedVoteIds: jsonb("revealed_vote_ids").notNull(),
  yesCount: integer("yes_count").notNull().default(0),
  noCount: integer("no_count").notNull().default(0),
  unsureCount: integer("unsure_count").notNull().default(0),
  truthProbabilitySumBps: integer("truth_probability_sum_bps").notNull().default(0),
  truthProbabilityCount: integer("truth_probability_count").notNull().default(0),
  evidenceRoot: text("evidence_root"),
  closed: boolean("closed").notNull().default(false),
  ...auditColumns(),
});

export const evidenceSubmissions = pgTable("evidence_submissions", {
  submissionId: text("submission_id").primaryKey(),
  evidenceId: text("evidence_id").notNull().unique(),
  claimId: text("claim_id").notNull(),
  phase: integer("phase").notNull(),
  sourceUrl: text("source_url"),
  submittedText: text("submitted_text"),
  sourceClass: text("source_class").notNull(),
  submittedBy: text("submitted_by"),
  retrievalStatus: text("retrieval_status").notNull(),
  rejectionCode: text("rejection_code"),
  ...auditColumns(),
});

export const evidenceArtifacts = pgTable("evidence_artifacts", {
  evidenceId: text("evidence_id").primaryKey(),
  submissionId: text("submission_id").notNull(),
  claimId: text("claim_id").notNull(),
  phase: integer("phase").notNull(),
  sourceClass: text("source_class"),
  sourceUrl: text("source_url").notNull(),
  finalUrl: text("final_url").notNull(),
  mimeType: text("mime_type").notNull(),
  byteLength: integer("byte_length").notNull(),
  contentHash: text("content_hash").notNull(),
  canonicalHash: text("canonical_hash").notNull(),
  rawWalrusBlobId: text("raw_walrus_blob_id").notNull(),
  rawWalrusObjectId: text("raw_walrus_object_id"),
  canonicalWalrusBlobId: text("canonical_walrus_blob_id").notNull(),
  canonicalWalrusObjectId: text("canonical_walrus_object_id"),
  walrusEndEpoch: bigint("walrus_end_epoch", { mode: "number" }),
  parserVersion: text("parser_version").notNull(),
  title: text("title"),
  excerpt: text("excerpt").notNull(),
  retrievedAt: text("retrieved_at").notNull(),
  ...auditColumns(),
});

export const evidenceManifests = pgTable(
  "evidence_manifests",
  {
    manifestId: text("manifest_id").primaryKey(),
    claimId: text("claim_id").notNull(),
    phase: integer("phase").notNull(),
    evidenceBundleId: text("evidence_bundle_id"),
    root: text("root").notNull(),
    manifestBlobId: text("manifest_blob_id").notNull(),
    manifestBlobObjectId: text("manifest_blob_object_id"),
    sourceCount: integer("source_count").notNull(),
    policyId: text("policy_id").notNull(),
    walrusEndEpoch: bigint("walrus_end_epoch", { mode: "number" }),
    sortedLeaves: jsonb("sorted_leaves").notNull(),
    transactionDigest: text("transaction_digest"),
    ...auditColumns(),
  },
  (table) => [uniqueIndex("evidence_manifests_claim_phase_uq").on(table.claimId, table.phase)],
);

export const inferenceRuns = pgTable("inference_runs", {
  runId: text("run_id").primaryKey(),
  claimId: text("claim_id").notNull(),
  phase: integer("phase").notNull(),
  agentProfileId: text("agent_profile_id").notNull(),
  jurySeatId: text("jury_seat_id").notNull(),
  attempt: integer("attempt").notNull(),
  providerId: text("provider_id").notNull(),
  modelId: text("model_id").notNull(),
  gonkaRequestId: text("gonka_request_id").notNull(),
  promptHash: text("prompt_hash").notNull(),
  inputHash: text("input_hash").notNull(),
  outputHash: text("output_hash").notNull(),
  runHash: text("run_hash"),
  runWalrusBlobId: text("run_walrus_blob_id"),
  runWalrusObjectId: text("run_walrus_object_id"),
  // Same trust boundary as vote_packages.salt_hex. Encrypt at rest before production.
  sealKeyHex: text("seal_key_hex"),
  sealIvHex: text("seal_iv_hex"),
  coreHash: text("core_hash"),
  sealedBlobId: text("sealed_blob_id"),
  sealedObjectId: text("sealed_object_id"),
  revealedBlobId: text("revealed_blob_id"),
  revealedObjectId: text("revealed_object_id"),
  toolTranscriptHash: text("tool_transcript_hash").notNull(),
  toolTranscriptWalrusBlobId: text("tool_transcript_walrus_blob_id"),
  toolTranscriptWalrusObjectId: text("tool_transcript_walrus_object_id"),
  walrusEndEpoch: bigint("walrus_end_epoch", { mode: "number" }),
  evidenceRoot: text("evidence_root").notNull(),
  validationStatus: text("validation_status").notNull(),
  latencyMs: integer("latency_ms").notNull(),
  inputTokens: integer("input_tokens"),
  outputTokens: integer("output_tokens"),
  output: jsonb("output"),
  audit: jsonb("audit").notNull(),
  // Public audit payload for seats that never produced a run hash.
  failure: jsonb("failure"),
  requestedAt: text("requested_at").notNull(),
  completedAt: text("completed_at").notNull(),
  ...auditColumns(),
});

export const runProofs = pgTable("run_proofs", {
  runId: text("run_id").primaryKey(),
  claimId: text("claim_id").notNull(),
  phase: integer("phase").notNull(),
  proofJson: text("proof_json").notNull(),
  builtAt: text("built_at").notNull(),
  ...auditColumns(),
});

export const deliberationTurns = pgTable("deliberation_turns", {
  turnId: text("turn_id").primaryKey(),
  claimId: text("claim_id").notNull(),
  ordinal: integer("ordinal").notNull(),
  ...auditColumns(),
});

export const toolCalls = pgTable(
  "tool_calls",
  {
    toolCallId: text("tool_call_id").primaryKey(),
    runId: text("run_id").notNull(),
    callIndex: integer("call_index").notNull(),
    toolName: text("tool_name").notNull(),
    argumentHash: text("argument_hash").notNull(),
    resultHash: text("result_hash"),
    status: text("status").notNull(),
    latencyMs: integer("latency_ms"),
    artifactHash: text("artifact_hash"),
    ...auditColumns(),
  },
  (table) => [uniqueIndex("tool_calls_run_index_uq").on(table.runId, table.callIndex)],
);

export const runApprovals = pgTable("run_approvals", {
  runApprovalId: text("run_approval_id").primaryKey(),
  runId: text("run_id").notNull().unique(),
  claimId: text("claim_id").notNull(),
  jurySeatId: text("jury_seat_id").notNull(),
  agentProfileId: text("agent_profile_id").notNull(),
  runHash: text("run_hash").notNull(),
  transactionDigest: text("transaction_digest").notNull(),
  attestor: text("attestor").notNull(),
  validationErrors: jsonb("validation_errors").notNull(),
  consumed: boolean("consumed").notNull().default(false),
  ...auditColumns(),
});

export const votePackages = pgTable(
  "vote_packages",
  {
    votePackageId: text("vote_package_id").primaryKey(),
    claimId: text("claim_id").notNull(),
    phase: integer("phase").notNull(),
    jurySeatId: text("jury_seat_id").notNull(),
    agentProfileId: text("agent_profile_id").notNull(),
    runId: text("run_id").notNull(),
    outcome: integer("outcome").notNull(),
    confidenceBps: integer("confidence_bps").notNull(),
    evidenceRoot: text("evidence_root").notNull(),
    outputHash: text("output_hash").notNull(),
    runHash: text("run_hash").notNull(),
    commitment: text("commitment").notNull(),
    saltHex: text("salt_hex").notNull(),
    commitmentTransactionDigest: text("commitment_transaction_digest"),
    committed: boolean("committed").notNull().default(false),
    revealed: boolean("revealed").notNull().default(false),
    ...auditColumns(),
  },
  (table) => [uniqueIndex("vote_packages_claim_phase_seat_uq").on(table.claimId, table.phase, table.jurySeatId)],
);

export const reveals = pgTable("reveals", {
  revealedVoteId: text("revealed_vote_id").primaryKey(),
  votePackageId: text("vote_package_id").notNull().unique(),
  claimId: text("claim_id").notNull(),
  phase: integer("phase").notNull(),
  roundTallyId: text("round_tally_id").notNull(),
  jurySeatId: text("jury_seat_id").notNull(),
  agentProfileId: text("agent_profile_id").notNull(),
  runId: text("run_id").notNull(),
  outcome: integer("outcome").notNull(),
  confidenceBps: integer("confidence_bps").notNull(),
  valid: boolean("valid").notNull(),
  transactionDigest: text("transaction_digest").notNull(),
  checkpoint: bigint("checkpoint", { mode: "number" }),
  ...auditColumns(),
});

export const resolutionCertificates = pgTable("resolution_certificates", {
  certificateId: text("certificate_id").primaryKey(),
  claimId: text("claim_id").notNull().unique(),
  result: text("result").notNull(),
  truthScoreBps: integer("truth_score_bps"),
  finalPhase: integer("final_phase").notNull(),
  finalRoundVoteIds: jsonb("final_round_vote_ids").notNull(),
  transactionDigest: text("transaction_digest").notNull(),
  checkpoint: bigint("checkpoint", { mode: "number" }),
  ...auditColumns(),
});

export const resolutionEvents = pgTable(
  "resolution_events",
  {
    eventId: text("event_id").primaryKey(),
    claimId: text("claim_id").notNull(),
    sequence: integer("sequence").notNull(),
    phase: text("phase").notNull(),
    kind: text("kind").notNull(),
    source: text("source").notNull(),
    visibility: text("visibility").notNull(),
    actorId: text("actor_id"),
    runId: text("run_id"),
    occurredAt: text("occurred_at").notNull(),
    publishedAt: text("published_at"),
    transactionDigest: text("transaction_digest"),
    checkpoint: bigint("checkpoint", { mode: "number" }),
    artifactHash: text("artifact_hash"),
    sourceCursor: text("source_cursor"),
    payload: jsonb("payload").notNull(),
    recordJson: jsonb("record_json").notNull(),
  },
  (table) => [
    uniqueIndex("resolution_events_claim_sequence_uq").on(table.claimId, table.sequence),
  ],
);

export const agentManifests = pgTable(
  "agent_manifests",
  {
    agentProfileId: text("agent_profile_id").notNull(),
    version: text("version").notNull(),
    owner: text("owner").notNull(),
    agentCapId: text("agent_cap_id"),
    manifestHash: text("manifest_hash").notNull(),
    manifestBlobId: text("manifest_blob_id").notNull(),
    modelId: text("model_id").notNull(),
    role: text("role").notNull(),
    active: boolean("active").notNull(),
    reputation: jsonb("reputation").notNull(),
    registeredCheckpoint: bigint("registered_checkpoint", { mode: "number" }).notNull(),
    ...auditColumns(),
  },
  (table) => [primaryKey({ columns: [table.agentProfileId, table.version] })],
);

export const payoutTickets = pgTable("payout_tickets", {
  payoutTicketId: text("payout_ticket_id").primaryKey(),
  claimId: text("claim_id").notNull(),
  recipient: text("recipient").notNull(),
  amount: text("amount").notNull(),
  coinType: text("coin_type").notNull(),
  reason: integer("reason").notNull(),
  consumed: boolean("consumed").notNull().default(false),
  createdTransactionDigest: text("created_transaction_digest").notNull(),
  consumedTransactionDigest: text("consumed_transaction_digest"),
  ...auditColumns(),
});

export const storageSchema = {
  claims,
  committees,
  jurySeats,
  roundTallies,
  evidenceSubmissions,
  evidenceArtifacts,
  evidenceManifests,
  inferenceRuns,
  runProofs,
  deliberationTurns,
  toolCalls,
  runApprovals,
  votePackages,
  reveals,
  resolutionCertificates,
  resolutionEvents,
  agentManifests,
  payoutTickets,
};
